--SESSION #1
BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED;
--SESSION #2
BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED;

--SESSION #1
SELECT SUM(rating)
FROM pizzeria;
--SESSION #2
INSERT INTO pizzeria (id, name, rating)
VALUES (10, 'Kazan Pizza', 5);
COMMIT;

--SESSION #1
SELECT SUM(rating)
FROM pizzeria;
COMMIT;
SELECT SUM(rating)
FROM pizzeria;
--SESSION #2
SELECT SUM(rating)
FROM pizzeria;